---
apiVersion: v1
kind: Secret
metadata:
  name: navigator-db-setup
data:
  navigator_db_setup.sh: "{{ lookup('template', 'templates/navigator/navigator_db_setup.sh') | b64encode }}"
  navigator_db_setup.sql: "{{ lookup('template', 'templates/navigator/navigator_db_setup.sql') | b64encode }}"
  navigator_testdb_setup.sql: "{{ lookup('template', 'templates/navigator/navigator_testdb_setup.sql') | b64encode }}"
type: Opaque

---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-navigator-db
spec:
  backoffLimit: 0
  # activeDeadlineSeconds: 100
  template:
    spec:
      containers:
        - env:
            - name: POSTGRES_HOSTNAME
              value: "{{ navigator_db_hostname }}"
            - name: POSTGRES_USER
              value: "{{ navigator_postgress_username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ navigator_postgress_password }}"

          name: navigator-db-init
          image: {{ navigator_db_image }}
          command: ['bash', '-c']
          args:
            - bash /tmp/navigator_db_setup.sh

          volumeMounts:
            - mountPath: /tmp/navigator_db_setup.sh
              name: navigator-db-setup
              readOnly: true
              subPath: navigator_db_setup.sh
            - mountPath: /tmp/navigator_db_setup.sql
              name: navigator-db-setup
              readOnly: true
              subPath: navigator_db_setup.sql
            - mountPath: /tmp/navigator_testdb_setup.sql
              name: navigator-db-setup
              readOnly: true
              subPath: navigator_testdb_setup.sql

      restartPolicy: Never
      volumes:
        - secret:
            secretName: navigator-db-setup
          name: navigator-db-setup
