- set_fact:
    k: "{{ lookup('varnames', item.secret_key)|length > 0 }}"

- name: Generate and update secret - {{ item.secret_key }}"
  block:
    - name: Get secret value from vault
      azure.azcollection.azure_rm_keyvaultsecret_info:
        vault_uri: "{{ keyvaulturi }}"
        name: "{{ item.vault_secret_key }}"
      register: vault_result

    # If secret was not found, generate it, set it and save
    - name: Generate Secret
      set_fact:
        "{{ item.secret_key }}": "{{ lookup('community.general.random_string', length=32, special=false) }}"
      when: vault_result.secrets | length == 0

    - name: Save to KeyVault
      azure.azcollection.azure_rm_keyvaultsecret:
        secret_name: "{{ item.vault_secret_key }}"
        secret_value: "{{ lookup('vars', item.secret_key) }}"
        keyvault_uri: "{{ keyvaulturi }}"
      when: vault_result.secrets | length == 0

    # If secret was found, set the secret value
    - name: Set secret value
      set_fact:
        "{{ item.secret_key }}": "{{ vault_result.secrets[0].secret }}"
      when: vault_result.secrets | length > 0

  when: not k

- assert:
    that: lookup('varnames', item.secret_key)|length > 0
    fail_msg: "{{  item.secret_key }} is not defined."
    quiet: true
