- name: Get secret value from vault
  azure.azcollection.azure_rm_keyvaultsecret_info:
    vault_uri: "{{ keyvaulturi }}"
    name: "{{ item.vault_secret_key }}"
  register: vault_result

- set_fact:
    secret_result: "{{ vault_result.secrets[0] }}"
  when: vault_result.secrets | length > 0

# If secret was not found, generate it, set it and save
- name: Generate Secret
  set_fact:
    "{{ item.secret_key }}": "{{ lookup('community.general.random_string', length=32, special=false) }}"
  when: not secret_result.secret

- name: Save to KeyVault
  azure.azcollection.azure_rm_keyvaultsecret:
    secret_name: "{{ item.vault_secret_key }}"
    secret_value: lookup('vars', "{{ item.secret_key }}")
    keyvault_uri: "{{ keyvaulturi }}"
  when: not secret_result.secret

# If secret was found, set the secret value
- name: Set secret value
  set_fact:
    "{{ item.secret_key }}": "{{ secret_result.secret }}"
  when: secret_result.secret

