---
- name: Load default variables
  include_vars: secrets.yml
  when: fjelltopp_env_type != 'local' and fjelltopp_cloud_provider != 'azure' and fjelltopp_cloud_provider != 'onprem'  # TODO tidy and make it == aws

- include_tasks: ./secrets.yml
  when: fjelltopp_env_type != 'local' and fjelltopp_cloud_provider != 'azure' and fjelltopp_cloud_provider != 'onprem'

- include_tasks: ./azure-secrets.yml
  when: fjelltopp_env_type != 'local' and fjelltopp_cloud_provider == 'azure' and fjelltopp_cloud_provider != 'onprem'

- include_tasks: ./onprem-secrets.yml
  when: fjelltopp_env_type != 'local' and fjelltopp_cloud_provider == 'onprem'

- include_role:
    name: k8s-context
  when: fjelltopp_env_type == 'local'

- include_tasks: ./azure-deploy.yml
  when: fjelltopp_cloud_provider == 'azure'

- include_tasks: ./deploy.yml
  when: fjelltopp_cloud_provider != 'azure' and fjelltopp_cloud_provider != 'onprem'

- include_tasks: ./onprem-deploy.yml
  when: fjelltopp_cloud_provider == 'onprem'
