- hosts: all
  connection: local
  become: false

  pre_tasks:
    - name: Downloading required collections
      command: "ansible-galaxy collection install -r roles/requirements.yml --force"
      delegate_to: localhost
      changed_when: false
      become: false
      tags: setup

- hosts: all
  connection: local
  become: false
  roles:
    - { role: navigator-build, tags: ["build", "all"] }
