- hosts: all
  connection: local
  become: false

  pre_tasks:
    - name: Downloading required roles
      command: "ansible-galaxy role install -r roles/requirements.yml --force"
      delegate_to: localhost
      changed_when: false
      become: false
      tags: setup
    - name: Downloading required collections
      command: "ansible-galaxy collection install -r roles/requirements.yml --force"
      delegate_to: localhost
      changed_when: false
      become: false
      tags: setup

- hosts: all
  connection: local
  become: false
  roles:
    - { role: gantsign.minikube, tags: ["setup", "all"] }
    - { role: geerlingguy.helm, tags: ["setup", "all"] }
    - { role: minikube-setup, tags: ["setup_arm_mac", "all"] }
