- hosts: all
  connection: local
  become: false

  pre_tasks:
    - name: Downloading required collections
      command: "ansible-galaxy collection install -r roles/requirements.yml --force"
      delegate_to: localhost
      changed_when: false
      become: false
      tags: setup

- hosts: all
  connection: local
  become: false
  roles:
    - { role: setup-aks, tags: ["setup", "all", "aks"] }
    - { role: setup-azure-frontdoor, tags: ["frontdoor"] }
    - { role: setup-azure-db, tags: ["db"] }
