- hosts: all
  connection: local
  become: false

  pre_tasks:
    - name: Downloading required collections
      command: "ansible-galaxy collection install -r roles/requirements.yml --force"
      delegate_to: localhost
      changed_when: false
      become: false
      tags: setup

- hosts: all
  connection: local
  become: false
  roles:
    - { role: setup-azure, tags: ["all", "bootstrap", "init", "post-init"] }
    - { role: setup-aks, tags: ["all", "setup", "aks", "init"] }
    - { role: setup-azure-db, tags: ["all", "db", "init"] }
    - { role: setup-azure-frontdoor, tags: ["all", "frontdoor", "post-init"] }
    # - { role: setup-azure-security, tags: ["all", "security", "post-init"] }
