apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: datapusher
  name: datapusher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datapusher
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: datapusher
    spec:
      containers:
        - image: {{ datapusher_image }}
          name: datapusher
          ports:
            - containerPort: 8800
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: datapusher
  name: datapusher
spec:
  ports:
    - name: "8800"
      port: 8800
      targetPort: 8800
  selector:
    app: datapusher
status:
  loadBalancer: {}
