---
apiVersion: v1
kind: Secret
metadata:
  name: ckan-db-backup
data:
  ckan_db_backup.sh: "{{ lookup('template', 'templates/ckan/db_backup.sh') | b64encode }}"
type: Opaque

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-ckan-db
spec:
  schedule: "17 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ckan-db-backup
            image: postgres:{{ ckan_backup_postgres_version }}
            command: ['bash', '-c']
            args:
              - bash /tmp/ckan_db_backup.sh

            volumeMounts:
              - mountPath: /tmp/ckan_db_backup.sh
                name: ckan-db-backup
                readOnly: true
                subPath: ckan_db_backup.sh

          restartPolicy: Never
          volumes:
            - secret:
                secretName: ckan-db-backup
              name: ckan-db-backup
      backoffLimit: 1
