---
apiVersion: v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: controller
        ports:
         - containerPort: 5432
           hostPort: 5432
         - containerPort: 6379
           hostPort: 6379
         - containerPort: 8983
           hostPort: 8983

