---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db
  name: db-external
  namespace: {{ application_namespace }}
spec:
  ports:
    - name: "db-external"
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: db
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis-external
  namespace: {{ application_namespace }}
spec:
  ports:
    - name: "redis-external"
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: solr
  name: solr-external
  namespace: {{ application_namespace }}
spec:
  ports:
    - name: "solr-external"
      port: 8983
      targetPort: 8983
      protocol: TCP
  selector:
    app: solr
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: tcp-services
  namespace: ingress-nginx
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"EnsureExists","app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx"},"name":"tcp-services","namespace":"ingress-nginx"}}
data:
  5432: "{{ application_namespace }}/db-external:5432"
  6379: "{{ application_namespace }}/redis-external:6379"
  8983: "{{ application_namespace }}/solr-external:8983"

---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
data:
  allow-snippet-annotations: "true"
