---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:jammy
    command:
      - "sleep"
      - "604800"
  hostNetwork: true
  dnsPolicy: Default
