apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
data:
  cluster.name: {{ eks_cluster_name }}
  http.port: '2020'
  http.server: 'On'
  logs.region: {{ aws_region }}
  logs.retention: "{{ cloudwatch_logs_retention }}"
  read.head: 'Off'
  read.tail: 'On'

