apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {{ k8s_cluster_output.certificate_authority.data }}
    server: {{ k8s_cluster_output.endpoint }}
  name: {{ k8s_cluster_output.arn }}
contexts:
- context:
    cluster: {{ k8s_cluster_output.arn }}
    user: {{ k8s_cluster_output.arn }}
  name: {{ k8s_cluster_output.arn }}
current-context: {{ k8s_cluster_output.arn }}
kind: Config
preferences: {}
users:
- name: {{ k8s_cluster_output.arn }}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - {{ aws_region }}
      - eks
      - get-token
      - --cluster-name
      - {{ eks_cluster_name }}
      command: aws
      env:
      - name: AWS_PROFILE
        value: "{{ lookup('env','AWS_PROFILE') }}"
