---
- name: Display Subnet id
  ansible.builtin.debug:
    var: vpc_output.stack_outputs.SubnetIds.split(',')[0]
  when: show_debug_output is defined

- name: Check if EFS cluster already exists
  community.aws.efs_info:
    aws_region: "{{ aws_region }}"
    tags:
        Name: "{{ eks_cluster_name }}-efs"
  register: efs_info
  become: false

# EFS setup should run only once, as the automated backup has to be run
# using aws cli, which doesn't work with Ansible EFS module (restricted tags).
# This is why we have a check above to see if EFS cluster with "our" name does exits.
# We're not checking if it's configured properly, as once the AWS Backup tags are
# added Ansible is unable to modify it.
- name: EFS provisioning
  block:
    - name: Create EFS cluster
      community.aws.efs:
        region: "{{ aws_region }}"
        state: present
        name: "{{ eks_cluster_name }}-efs"
        encrypt: yes
        tags:
          Name: "{{ eks_cluster_name }}-efs"
        targets:
            - subnet_id: "{{ vpc_output.stack_outputs.SubnetIds.split(',')[0] }}"
              security_groups: [ "{{ eks_node_info.instances[0].network_interfaces[0].groups[0].group_id }}" ]
      register: efs_creation_output

    - name: Enable automated EFS backups
      shell: aws efs put-backup-policy --region "{{ aws_region }}" --file-system-id "{{ efs_creation_output.efs.file_system_id }}" --backup-policy Status="ENABLED"
  when: efs_info.efs[0].name is not defined
  become: false

# Once created, NFS provisioner can't be modified, as it's "immutable" (storage class in use)
# any changes here will not work, especially EFS endpoint change or mount options
- name: NFS provisioner
  block:
    - name: Add NFS provisioner HELM repository
      kubernetes.core.helm_repository:
        name: nfs-subdir-external-provisioner
        repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

    - name: Deploy NFS provisioner
      kubernetes.core.helm:
        update_repo_cache: yes
        name: nfs-subdir-external-provisioner
        chart_repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
        chart_ref: nfs-subdir-external-provisioner
        kubeconfig: "{{ kubeconfig }}"
        namespace: "default"
        values:
          storageClass:
            name: "efs-client"
            archiveOnDelete: true
            accessModes: ReadWriteMany
          nfs:
            server: "{{ efs_creation_output.efs.mount_targets[0].ip_address }}"
            path: "/"
            mountOptions:
              - nfsvers=4.1
              - rsize=1048576
              - wsize=1048576
              - hard
              - timeo=600
              - retrans=2
              - noresvport
  become: false
  when: efs_creation_output.efs.mount_targets[0].ip_address is defined

