- name: Add Datadog Helm repo
  kubernetes.core.helm_repository:
    name: datadog
    repo_url: https://helm.datadoghq.com
  when: datadog_api_key is defined

- name: Install Datadog Operator
  kubernetes.core.helm:
    name: datadog-operator
    chart_ref: datadog/datadog-operator
    release_namespace: default
    kubeconfig: "{{ kubeconfig | default(lookup('env', 'HOME') + '/.kube/config') }}"
  when: datadog_api_key is defined

- name: Create Datadog secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: datadog-secret
        namespace: default
      type: Opaque
      stringData:
        api-key: "{{ datadog_api_key }}"
    kubeconfig: "{{ kubeconfig | default(lookup('env', 'HOME') + '/.kube/config') }}"
  when: datadog_api_key is defined

- name: Deploy Datadog Agent
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'kubernetes/datadog-agent.yaml') | from_yaml_all | list }}"
    kubeconfig: "{{ kubeconfig | default(lookup('env', 'HOME') + '/.kube/config') }}"
  when: datadog_api_key is defined
