 
# No ansible for this, so using CLI mostly
# Command group 'afd' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
- name: Get subscription_id for later
  azure.azcollection.azure_rm_subscription_info:
    all: true
  register: subscription_output

- name: Create Front Door Profile
  command: >
    az afd profile create \
    --profile-name {{resource_prefix}}-afd \
    --resource-group {{ resource_group_name }} \
    --sku Premium_AzureFrontDoor

- name: Create Front Door Endpoint For Ckan
  command: >
    az afd endpoint create \
      --resource-group {{ resource_group_name }} \
      --profile-name {{resource_prefix}}-afd \
      --endpoint-name {{resource_prefix|lower}}-ckan \
      --enabled-state Enabled

- name: Create Front Door Endpoint For Giftless
  command: >
    az afd endpoint create \
      --resource-group {{ resource_group_name }} \
      --profile-name {{resource_prefix}}-afd \
      --endpoint-name {{resource_prefix|lower}}-giftless \
      --enabled-state Enabled

# Origin Groups
- name: Create Front Door Origin Group (CKAN)
  command: >      
    az afd origin-group create \
    --resource-group {{ resource_group_name }} \
    --profile-name {{resource_prefix}}-afd \
    --origin-group-name {{resource_prefix}}-og-ckan \
    --probe-request-type GET \
    --probe-protocol Http \
    --probe-interval-in-seconds 60 \
    --probe-path / \
    --sample-size 4 \
    --successful-samples-required 3 \
    --additional-latency-in-milliseconds 50

# Origin Groups
- name: Create Front Door Origin Group (giftless)
  command: >      
    az afd origin-group create \
    --resource-group {{ resource_group_name }} \
    --profile-name {{resource_prefix}}-afd \
    --origin-group-name {{resource_prefix}}-og-giftless \
    --probe-request-type GET \
    --probe-protocol Http \
    --probe-interval-in-seconds 60 \
    --probe-path / \
    --sample-size 4 \
    --successful-samples-required 3 \
    --additional-latency-in-milliseconds 50

# get details for the Private Link Service that has been created for the CKAN k8s service
- name: Get Private Link Service details (ckan)
  command: >
    az network private-link-service show \
    --name {{ ckan_pls_name }} \
    --resource-group "{{ node_group_name }}" \
    -o json
  register: ckan_pls_output

- set_fact:
    ckan_pls_alias: "{{ (ckan_pls_output.stdout|from_json).alias }}"

- name: Show pls
  debug: "msg={{ ckan_pls_alias }}"

- name: Create an origin with Private Link to AKS (CKAN)
  command: >
      az afd origin create -g group 
      --host-name {{ ckan_pls_alias }} \
      --origin-host-header {{ ckan_fqdn }} \
      --resource-group {{ resource_group_name }} \
      --profile-name {{resource_prefix}}-afd \
      --origin-group-name {{resource_prefix}}-og-ckan \
      --origin-name ckan-origin \ 
      --priority 1 \
      --weight 1000 \
      --enabled-state Enabled \
      --http-port 80 \
      --https-port 80 \ 
      --enable-private-link true \
      --private-link-resource "/subscriptions/{{ subscription_output.subscriptions[0].subscription_id }}/resourceGroups/{{ node_group_name }}/providers/Microsoft.Network/privateLinkServices/{{ ckan_pls_name }}" \
      --private-link-request-message 'Please approve this request' \
      --private-link-location {{ azure_region }}


- name: Get Private Link Service details (giftless)
  command: >
    az network private-link-service show \
    --name {{ giftless_pls_name }} \
    --resource-group "{{ node_group_name }}" \
    -o json
  register: giftless_pls_output

- set_fact:
    giftless_pls_alias: "{{ (giftless_pls_output.stdout|from_json).alias }}"

- name: Create an origin with Private Link to AKS (Giftless)
  command: >
      az afd origin create -g group 
      --host-name {{ giftless_pls_alias }} \
      --origin-host-header {{ giftless_pls_alias }} \
      --resource-group {{ resource_group_name }} \
      --profile-name {{resource_prefix}}-afd \
      --origin-group-name {{resource_prefix}}-og-giftless \
      --origin-name ckan-origin \ 
      --priority 1 \
      --weight 1000 \
      --enabled-state Enabled \
      --enable-private-link true \
      --http-port 5001 \
      --https-port 5001 \ 
      --private-link-resource "/subscriptions/{{ subscription_output.subscriptions[0].subscription_id }}/resourceGroups/{{ node_group_name }}/providers/Microsoft.Network/privateLinkServices/{{ giftless_pls_name }}" \
      --private-link-request-message 'Please approve this request' \
      --private-link-location {{ azure_region }}

- name: Create route for CKAN
  command: >
    az afd route create \
    --resource-group {{ resource_group_name }} \
    --profile-name {{resource_prefix}}-afd \
    --route-name ckan-route \
    --endpoint-name {{resource_prefix|lower}}-ckan \
    --patterns '/*' \
    --origin-group {{resource_prefix}}-og-ckan \
    --enabled-state Enabled \
    --supported-protocols Https \
    --link-to-default-domain Enabled \
    --https-redirect Enabled \
    --forwarding-protocol HttpOnly

- name: Create route for Giftless
  command: >
    az afd route create \
    --resource-group {{ resource_group_name }} \
    --profile-name {{resource_prefix}}-afd \
    --route-name giftless-route \
    --endpoint-name {{resource_prefix|lower}}-giftless \
    --patterns '/*' \
    --origin-group {{resource_prefix}}-og-giftless \
    --enabled-state Enabled \
    --supported-protocols Https \
    --link-to-default-domain Enabled \
    --https-redirect Enabled \
    --forwarding-protocol HttpOnly

- name: Get PLS details for approval (CKAN)
  command: >
    az network private-endpoint-connection list \ 
    --id /subscriptions/{{ subscription_output.subscriptions[0].subscription_id }}/resourceGroups/{{ node_group_name }}/providers/Microsoft.Network/privateLinkServices/{{ ckan_pls_name }} \
    -o json
  register: ckan_pls_pending_output

- name: Get PLS details for approval (giftless)
  command: >
    az network private-endpoint-connection list \ 
    --id /subscriptions/{{ subscription_output.subscriptions[0].subscription_id }}/resourceGroups/{{ node_group_name }}/providers/Microsoft.Network/privateLinkServices/{{ giftless_pls_name }} \
    -o json
  register: giftless_pls_pending_output

- name: Approve the Private Link Services (Giftless)
  command: >
    az network private-endpoint-connection approve \ 
    -g {{ node_group_name }} \
    --type Microsoft.Network/privateLinkServices \
    --resource-name {{ giftless_pls_name }} 
    -n {{ (giftless_pls_pending_output.stdout|from_json)[0].name }}
    --description "Approved"
  when: (giftless_pls_pending_output.stdout|from_json)[0].properties.privateLinkServiceConnectionState.status == "Pending"

- name: Approve the Private Link Services (CKAN)
  command: >
    az network private-endpoint-connection approve \ 
    -g {{ node_group_name }} \
    --type Microsoft.Network/privateLinkServices \
    --resource-name {{ ckan_pls_name }} 
    -n {{ (ckan_pls_pending_output.stdout|from_json)[0].name }}
    --description "Approved"
  when: (ckan_pls_pending_output.stdout|from_json)[0].properties.privateLinkServiceConnectionState.status == "Pending"
