CREATE DATABASE navigator_engine ENCODING UTF8;
CREATE DATABASE navigator_api ENCODING UTF8;

CREATE ROLE engine NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD '{{ navigator_engine_db_pw }}';
GRANT ALL ON DATABASE navigator_engine TO engine;
CREATE ROLE api NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD '{{ navigator_api_db_pw }}';
GRANT ALL ON DATABASE navigator_api TO api;
