---
apiVersion: v1
kind: Secret
metadata:
  name: db-bootstrap
data:
  db_bootstrap.sh: "{{ lookup('template', 'templates/dhis2/db_init.sh') | b64encode }}"
  db_bootstrap.sql: "{{ lookup('template', 'templates/dhis2/db_init.sql') | b64encode }}"
  db_bootstrap_postgis.sql: "{{ lookup('template', 'templates/dhis2/db_init_postgis.sql') | b64encode }}"
type: Opaque

---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-db-accounts
spec:
  backoffLimit: 0
  # activeDeadlineSeconds: 100
  template:
    spec:
      containers:
        - env:
            - name: POSTGRES_HOSTNAME
              value: "{{ db_hostname }}"
            - name: POSTGRES_USER
              value: "{{ rds_admin_username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ lookup('aws_secret', application_namespace + '_rds_admin_pw' , region = aws_region ) }}"
          name: db-init
          image: "{{ postgresql_image }}"
          command: ['bash', '-c']
          args:
            - bash /tmp/db_bootstrap.sh

          volumeMounts:
            - mountPath: /tmp/db_bootstrap.sh
              name: db-bootstrap
              readOnly: true
              subPath: db_bootstrap.sh
            - mountPath: /tmp/db_bootstrap.sql
              name: db-bootstrap
              readOnly: true
              subPath: db_bootstrap.sql
            - mountPath: /tmp/db_bootstrap_postgis.sql
              name: db-bootstrap
              readOnly: true
              subPath: db_bootstrap_postgis.sql

      restartPolicy: Never
      volumes:
        - secret:
            secretName: db-bootstrap
          name: db-bootstrap

