---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dhis2-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  rules:
    - host: "{{ dhis2_fqdn }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dhis2
                port:
                  name: dhis2

