---
apiVersion: v1
kind: Secret
metadata:
  name: metadata-import
data:
  import_metadata.sh: "{{ lookup('template', 'templates/dhis2/import_metadata.sh') | b64encode }}"
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: admin-pw-change
data:
  admin_pw_change.sh: "{{ lookup('template', 'templates/dhis2/admin_pw_change.sh') | b64encode }}"
type: Opaque

---
apiVersion: batch/v1
kind: Job
metadata:
  name: import-metadata
spec:
  backoffLimit: 5
  template:
    spec:
      initContainers:
        - env:
            - name: DHIS2_HOME
              value: /etc/dhis2/
          image: {{ tomcat_image }}
          imagePullPolicy: Always
          name: dhis2-metadata-import

          command: ['bash', '-c']
          args:
            - sleep 60 && bash /tmp/import_metadata.sh

          volumeMounts:
            - mountPath: /tmp/import_metadata.sh
              name: metadata-import
              readOnly: true
              subPath: import_metadata.sh

      containers:
        - env:
            - name: POSTGRES_HOSTNAME
              value: "{{ db_hostname }}"
          name: db-admin-pw-change
          image: {{ tomcat_image }}
          command: ['bash', '-c']
          args:
            - bash /tmp/admin_pw_change.sh

          volumeMounts:
            - mountPath: /tmp/admin_pw_change.sh
              name: admin-pw-change
              readOnly: true
              subPath: admin_pw_change.sh


      restartPolicy: Never
      volumes:
        - secret:
            secretName: metadata-import
          name: metadata-import
        - secret:
            secretName: admin-pw-change
          name: admin-pw-change

