- set_fact:
    k: "{{ lookup('varnames', item.secret_key)|length > 0 }}"

- name: Generate and update secret - {{ item.secret_key }}"
  block:
    - name: Get secret value from vault
      command: >
        az keyvault secret show
        --vault-name {{ shared_vault_name }}
        --name {{ item.vault_secret_key }}
        --query value -o tsv
      register: vault_result
      failed_when: false
      changed_when: false

    # If secret was not found, generate it, set it and save
    - name: Generate Secret
      set_fact:
        "{{ item.secret_key }}": "{{ lookup('community.general.random_string', length=32, special=false) }}"
      when: vault_result.rc != 0

    - name: Save to KeyVault
      command: >
        az keyvault secret set
        --vault-name {{ shared_vault_name }}
        --name {{ item.vault_secret_key }}
        --value "{{ lookup('vars', item.secret_key) }}"
      when: vault_result.rc != 0

    # If secret was found, set the secret value
    - name: Set secret value
      set_fact:
        "{{ item.secret_key }}": "{{ vault_result.stdout | trim }}"
      when: vault_result.rc == 0

  when: not k

- assert:
    that: lookup('varnames', item.secret_key)|length > 0
    fail_msg: "{{  item.secret_key }} is not defined."
    quiet: true
