---
apiVersion: v1
kind: Service
metadata:
  name: ckan-ingress
spec:
  type: LoadBalancer
  selector:
    app: ckan
  ports:
    - name: ckan
      protocol: TCP
      port: 80
      targetPort: 5000