---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ckan-storage
spec:
  storageClassName: "{{ storage_class_name }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ckan-webassets
spec:
  storageClassName: "{{ storage_class_name }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ckan
  name: ckan-resources
spec:
  storageClassName: "{{ storage_class_name }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

