---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:  
  name: azureblob-nfs-premium
provisioner: file.csi.azure.com
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - uid=900
  - gid=900

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ckan
  name: ckan-resources
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azureblob-nfs-premium
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ckan
  name: ckan-webassets
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azureblob-nfs-premium
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ckan
  name: ckan-storage
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azureblob-nfs-premium
  resources:
    requests:
      storage: 1Gi
