---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: ckan-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    volumeHandle: "{{ disk_prefix }}ckan-storage"
    volumeAttributes:
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: ckan-webassets
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    volumeHandle: "{{ disk_prefix }}ckan-webassets"
    volumeAttributes:
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
  name: ckan-resources
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    volumeHandle: "{{ disk_prefix }}ckan-resources"
    volumeAttributes:
      fsType: ext4            

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ckan-storage
spec:
  storageClassName: "{{ storage_class_name }}"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ckan-webassets
spec:
  storageClassName: "{{ storage_class_name }}"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ckan
  name: ckan-resources
spec:
  storageClassName: "{{ storage_class_name }}"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}

