---
apiVersion: v1
kind: Secret
metadata:
  name: odk-frontend-config
data:
  odk.conf: "{{ lookup('template', 'templates/odk/frontend-nginx.conf')| b64encode }}"
type: Opaque


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odk-frontend
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: odk
      component: odk-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: odk
        component: odk-frontend
    spec:
      containers:
        - name: odk-frontend
          image: {{ odk_frontend_image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: odk-frontend-config
              mountPath: /etc/nginx/conf.d/odk.conf
              subPath: odk.conf
      restartPolicy: Always
      volumes:
        - name: odk-frontend-config
          secret:
            secretName: odk-frontend-config

---
apiVersion: v1
kind: Service
metadata:
  name: odk-frontend
  labels:
    app: odk
    component: odk-frontend
spec:
  selector:
   app: odk
   component: odk-frontend
  ports:
    - name: "http"
      port: 80
      targetPort: 80
status:
  loadBalancer: {}

