---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ckan-storage
  creationTimestamp: null
  labels:
    app: ckan
spec:
  storageClassName: "{{ storage_class_name }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: ckan
  name: ckan-webassets
spec:
  storageClassName: "{{ storage_class_name }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: ckan
  name: ckan-resources
spec:
  storageClassName: "{{ storage_class_name }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
