# MAKE SURE THE CERT PROVIDED HAS THE FULL INTERMEDIATE CHAIN
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripgiftlessprefix
  namespace: {{ ckan_namespace }}
spec:
  stripPrefix:
    prefixes:
      - "/giftless"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  generation: 1
  name: ckan-ingress
  namespace: {{ ckan_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ ckan_namespace }}-stripgiftlessprefix@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
     - hosts:
        - {{ ckan_tls_name }}
       secretName: {{ ckan_tls_name }}-tls-cert
  ingressClassName: traefik
  rules:
  - host: {{ ckan_tls_name }}
    http:
      paths:
      - backend:
          service:
            name: giftless
            port:
              number: 5001
        path: /giftless
        pathType: Prefix
      - backend:
          service:
            name: ckan
            port:
              number: 5000
        path: /
        pathType: Prefix
