---
apiVersion: v1
kind: Secret
metadata:
  name: ckan-db-bootstrap
data:
  ckan_db_bootstrap.sh: "IyEvYmluL2Jhc2gKc2V0IC14CmV4cG9ydCBQR1BBU1NXT1JEPSIkUE9TVEdSRVNfUEFTU1dPUkQiCnBzcWwgLWggIiRQT1NUR1JFU19IT1NUTkFNRSIgLS11c2VybmFtZT0iJFBPU1RHUkVTX1VTRVIiIC1kIHBvc3RncmVzIC1mIC90bXAvY2thbl9kYl9ib290c3RyYXAuc3FsCg=="
  ckan_db_bootstrap.sql: "LyogYmFzZWQgb24gaHR0cHM6Ly9mamVsbHRvcHAuYXRsYXNzaWFuLm5ldC93aWtpL3NwYWNlcy9BRFIvcGFnZXMvMTQwOTAzMi9BRFIrQmFja3VwK3Jlc3RvcmUgKi8KQ1JFQVRFIEVYVEVOU0lPTiBQT1NUR0lTOwpDUkVBVEUgUk9MRSBja2FuIE5PU1VQRVJVU0VSIE5PQ1JFQVRFREIgTk9DUkVBVEVST0xFIExPR0lOIFBBU1NXT1JEICd0ZTE0MkFTRFMowqMkJkApKEAkKilAKiRtcCEhISEhISEhISEnOwpDUkVBVEUgUk9MRSBkYXRhc3RvcmVfcm8gTk9TVVBFUlVTRVIgTk9DUkVBVEVEQiBOT0NSRUFURVJPTEUgTE9HSU4gUEFTU1dPUkQgJ3RlMTQyQVNEUyjCoyQmQCkoQCQqKUAqJG1wISEhISEhISEhISc7CkNSRUFURSBST0xFIGRhdGFzdG9yZSBOT1NVUEVSVVNFUiBOT0NSRUFURURCIE5PQ1JFQVRFUk9MRSBMT0dJTiBQQVNTV09SRCAndGUxNDJBU0RTKMKjJCZAKShAJCopQCokbXAhISEhISEhISEhJzsKR1JBTlQgY2thbiB0byBja2FuX2FkbWluOwpHUkFOVCBkYXRhc3RvcmUgdG8gY2thbl9hZG1pbjsKR1JBTlQgZGF0YXN0b3JlIHRvIGNrYW47CkFMVEVSIFNDSEVNQSBwdWJsaWMgT1dORVIgdG8gY2thbjsKR1JBTlQgQUxMIE9OIFNDSEVNQSBwdWJsaWMgVE8gY2thbjsKR1JBTlQgQUxMIFBSSVZJTEVHRVMgT04gQUxMIFRBQkxFUyBJTiBTQ0hFTUEgcHVibGljIFRPIGNrYW47CkNSRUFURSBEQVRBQkFTRSBja2FuIE9XTkVSIGNrYW4gRU5DT0RJTkcgJ3V0Zi04JzsKQUxURVIgVklFVyBnZW9ncmFwaHlfY29sdW1ucyBPV05FUiBUTyBja2FuOwpBTFRFUiBWSUVXIGdlb21ldHJ5X2NvbHVtbnMgT1dORVIgVE8gY2thbjsKQUxURVIgVEFCTEUgc3BhdGlhbF9yZWZfc3lzIE9XTkVSIFRPIGNrYW47CkNSRUFURSBEQVRBQkFTRSBkYXRhc3RvcmUgT1dORVIgY2thbiBFTkNPRElORyAndXRmLTgnOwpHUkFOVCBBTEwgUFJJVklMRUdFUyBPTiBEQVRBQkFTRSBja2FuIHRvIGNrYW47CkdSQU5UIEFMTCBQUklWSUxFR0VTIE9OIERBVEFCQVNFIGRhdGFzdG9yZSBUTyBja2FuOwpHUkFOVCBBTEwgUFJJVklMRUdFUyBPTiBEQVRBQkFTRSBkYXRhc3RvcmUgVE8gZGF0YXN0b3JlOwpSRVZPS0UgQUxMIE9OIFRBQkxFIHB1YmxpYy5zcGF0aWFsX3JlZl9zeXMgRlJPTSByZHNhZG1pbjsKUkVWT0tFIFNFTEVDVCBPTiBUQUJMRSBwdWJsaWMuc3BhdGlhbF9yZWZfc3lzIEZST00gUFVCTElDOwpHUkFOVCBBTEwgb24gVEFCTEUgcHVibGljLnNwYXRpYWxfcmVmX3N5cyBUTyBja2FuX2FkbWluOwpHUkFOVCBBTEwgT04gVEFCTEUgcHVibGljLnNwYXRpYWxfcmVmX3N5cyBUTyBja2FuOwpHUkFOVCBTRUxFQ1QgT04gVEFCTEUgcHVibGljLnNwYXRpYWxfcmVmX3N5cyBUTyBQVUJMSUM7CkdSQU5UIFNFTEVDVCBPTiBUQUJMRSBwdWJsaWMuc3BhdGlhbF9yZWZfc3lzIFRPIGRhdGFzdG9yZV9ybzsKUkVWT0tFIEFMTCBPTiBUQUJMRSBwdWJsaWMuZ2VvbWV0cnlfY29sdW1ucyBGUk9NIHJkc2FkbWluOwpSRVZPS0UgU0VMRUNUIE9OIFRBQkxFIHB1YmxpYy5nZW9tZXRyeV9jb2x1bW5zIEZST00gUFVCTElDOwpHUkFOVCBBTEwgT04gVEFCTEUgcHVibGljLmdlb21ldHJ5X2NvbHVtbnMgVE8gY2thbjsKR1JBTlQgU0VMRUNUIE9OIFRBQkxFIHB1YmxpYy5nZW9tZXRyeV9jb2x1bW5zIFRPIFBVQkxJQzsKR1JBTlQgU0VMRUNUIE9OIFRBQkxFIHB1YmxpYy5nZW9tZXRyeV9jb2x1bW5zIFRPIGRhdGFzdG9yZV9ybzsKR1JBTlQgQ09OTkVDVCBPTiBEQVRBQkFTRSBkYXRhc3RvcmUgVE8gZGF0YXN0b3JlX3JvOwpHUkFOVCBVU0FHRSBPTiBTQ0hFTUEgcHVibGljIFRPIGRhdGFzdG9yZV9ybzsKR1JBTlQgU0VMRUNUIE9OIEFMTCBUQUJMRVMgSU4gU0NIRU1BIHB1YmxpYyBUTyBkYXRhc3RvcmVfcm87CkdSQU5UIFNFTEVDVCBPTiBBTEwgU0VRVUVOQ0VTIElOIFNDSEVNQSBwdWJsaWMgVE8gZGF0YXN0b3JlX3JvOwpSRVZPS0UgQUxMIG9uIFRBQkxFIHB1YmxpYy5zcGF0aWFsX3JlZl9zeXMgRlJPTSBja2FuX2FkbWluOwpSRVZPS0UgY2thbiBmcm9tIGNrYW5fYWRtaW47ClJFVk9LRSBkYXRhc3RvcmUgZnJvbSBja2FuX2FkbWluOwoK"
type: Opaque

---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-ckan-db-accounts
spec:
  backoffLimit: 0
  # activeDeadlineSeconds: 100
  template:
    spec:
      containers:
        - env:
            - name: POSTGRES_HOSTNAME
              value: "fjelltoppckan-d-db.postgres.database.azure.com"
            - name: POSTGRES_USER
              value: "ckan_admin"
            - name: POSTGRES_PASSWORD
              value: "te142ASDS(£$&@)(@$*)@*$mp!!!!!!!!!!"
          name: ckan-db-init
          image: postgres:13
          command: ['bash', '-c']
          args:
            - bash /tmp/ckan_db_bootstrap.sh

          volumeMounts:
            - mountPath: /tmp/ckan_db_bootstrap.sh
              name: ckan-db-bootstrap
              readOnly: true
              subPath: ckan_db_bootstrap.sh
            - mountPath: /tmp/ckan_db_bootstrap.sql
              name: ckan-db-bootstrap
              readOnly: true
              subPath: ckan_db_bootstrap.sql

      restartPolicy: Never
      volumes:
        - secret:
            secretName: ckan-db-bootstrap
          name: ckan-db-bootstrap

