apiVersion: v1
kind: ServiceAccount
metadata:
  name: ckan-ckan-operator
  namespace: {{ application_namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ckan-ckan-operator-role
  namespace: {{ application_namespace }}
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/portforward
    verbs: ["list", "get", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ckan-ckan-operator-rolebinding
  namespace: {{ application_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ckan-ckan-operator-role
  namespace: {{ application_namespace }}
subjects:
- kind: ServiceAccount
  name: ckan-ckan-operator
  namespace: {{ application_namespace }}
