apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {{ lookup('aws_secret', "eks_" + eks_cluster_name + "_ca" , region = aws_region ) }}
    server: {{ lookup('aws_secret', "eks_" + eks_cluster_name + "_endpoint" , region = aws_region ) }}
  name:  {{ lookup('aws_secret', "eks_" + eks_cluster_name + "_arn" , region = aws_region ) }}
contexts:
- context:
    cluster: {{ lookup('aws_secret', "eks_" + eks_cluster_name + "_arn" , region = aws_region ) }}
    user: {{ lookup('aws_secret', "eks_" + eks_cluster_name + "_arn" , region = aws_region ) }}
  name: {{ lookup('aws_secret', "eks_" + eks_cluster_name + "_arn" , region = aws_region ) }}
current-context: {{ lookup('aws_secret', "eks_" + eks_cluster_name + "_arn" , region = aws_region ) }}
kind: Config
preferences: {}
users:
- name: {{ lookup('aws_secret', "eks_" + eks_cluster_name + "_arn" , region = aws_region ) }}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - {{ aws_region }}
      - eks
      - get-token
      - --cluster-name
      - {{ eks_cluster_name }}
      command: aws
{% if AWS_PROFILE is defined %}
      env:
      - name: AWS_PROFILE
        value: "{{ lookup('env','AWS_PROFILE') }}"
{% endif %}
