TRANSFER_ADAPTERS:
  basic:
    factory: giftless.transfer.basic_streaming:factory
    options:
{% if giftless_s3_bucket is defined %}
      storage_class: giftless.storage.amazon_s3:AmazonS3Storage
      storage_options:
        bucket_name: {{ giftless_s3_bucket }}
{% elif giftless_azure_blob_string is defined %}        
      storage_class: giftless.storage.azure:AzureBlobsStorage
      storage_options:
        connection_string: "{{ giftless_azure_blob_string }}"
        container_name: "{{ resource_prefix|lower }}-datalake"
{% else %}
      storage_class: giftless.storage.local_storage:LocalStorage
{% endif %}
AUTH_PROVIDERS:
  - factory: giftless.auth.jwt:factory
    options:
      algorithm: RS256
      public_key_file: /app/jwt-rs256.key.pub
MIDDLEWARE:
  - class: werkzeug.middleware.proxy_fix:ProxyFix
    kwargs:
      x_host: 1
      x_port: 1
      x_prefix: 1

